combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
edition = "2018"
format_strings = true
imports_layout = "HorizontalVertical"
max_width = 120
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
space_after_colon = true
trailing_semicolon = true
use_try_shorthand = true
wrap_comments = true
